### ISSUE TITLE
Got IndexError when processing raw data

### ISSUE THREAD

**Issue by GaoCheng22** [jmetz/mmhelper#4]
It's a great tool, I love it！
I got an error when processing data, i have tried 3 installation methods, and it occured same error.
It can only output every frame images.
![微信图片_20240328222712](https://github.com/jmetz/mmhelper/assets/118256867/74dc8de0-3f4c-4348-850e-463aa3686316)

**Comment by jmetz** [comment]
Thanks for reporting this. From your screenshot, it's clear that `mmhelper` is failing to detect wells in your images (`seps2_sorted` is empty). 

This means that at present, `mmhelper` can't process this dataset; to determine why, you could set pass the `--debug` flag whet you run it, as this should produce the most debugging information to determine why it's failing. 

Closing as this isn't a bug per se, but rather likely to be either a limitation of `mmhelper` in terms of not being able to process this dataset, or an issue with the dataset itself.
